voice_group bramble_blast
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 226, 0, 38 @ 0 - bramble lead
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 1 - strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 127 @ 2 - steel guitar
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar_bramble_solo, 255, 249, 25, 127 @ 3 - guitar solo
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 4 - violin
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 5 - cello
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149 @ 6 - bass
	voice_keysplit_all voicegroup_bramble_blast_drumset @ 7 - drums
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 8 - reverse cymbal substitute
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 9 - synth strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 @ 10 - celesta
