voice_group fire_and_flames
	voice_keysplit_all voicegroup_fire_and_flames_drumset @ 0 - drums
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127 @ 1 - 8-bit square
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 127 @ 2 - bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149 @ 3 - bass guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 127 @ 4 - distortion guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127 @ 5 - distortion guitar 2
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 255, 127 @ 6 - koto
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano @ 7 - harpsichord
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127 @ 8 - 8-bit sine
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127 @ 9 - 8-bit triangle
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 10 - strings
