voice_group hopes_and_dreams
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 0 - strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 @ 1 - vibraphone
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 2 - violin
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 195 @ 3 - overdriven guitar
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127 @ 4 - square lead
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 127 @ 5 - bass + lead
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204 @ 6 - marimba
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 127 @ 7 - low guitar part as synth bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 8 - reverse cymbal substitute
	voice_keysplit_all voicegroup_hopes_and_dreams_drumset @ 9 - drums
