voice_group live_and_learn
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127 @ 0 - electric guitar
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano @ 1 - grand piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149 @ 2 - bass guitar
	voice_directsound 60, 0, DirectSoundWaveData_synth_pluck, 255, 0, 255, 127 @ 3 - saw lead
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 249, 0, 165 @ 4 - electric piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 @ 5 - steel drums
	voice_keysplit_all voicegroup_live_and_learn_drumset @ 6 - drums
