voice_group rasputin
	voice_keysplit_all voicegroup_rasputin_drumset @ 0 - drums
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 255, 127 @ 1 - koto
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149 @ 2 - bass guitar
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings @ 3 - violin
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 127 @ 4 - jazz guitar
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano @ 5 - grand piano
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 249, 0, 165 @ 6 - electric piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 254, 0, 127 @ 7 - slap bass
