voice_group son_of_flynn
	voice_directsound 60, 0, DirectSoundWaveData_synth_pluck, 255, 0, 255, 127 @ 0 - synth pluck
	voice_directsound 60, 0, DirectSoundWaveData_synth_pluck, 255, 0, 255, 100 @ 1 - smooth synth
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 127 @ 2 - synth bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188 @ 3 - church organ
