#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_CUSTOM_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_CUSTOM_MONS_H

//Generic Mons

#define CUSTOM_FRONTIER_MON_VENUSAUR_GENERIC_1 0
#define CUSTOM_FRONTIER_MON_VENUSAUR_GENERIC_2 1
#define CUSTOM_FRONTIER_MON_CHARIZARD_GENERIC_1 2
#define CUSTOM_FRONTIER_MON_CHARIZARD_GENERIC_2 3
#define CUSTOM_FRONTIER_MON_BLASTOISE_GENERIC_1 4
#define CUSTOM_FRONTIER_MON_BLASTOISE_GENERIC_2 5
#define CUSTOM_FRONTIER_MON_BUTTERFREE_GENERIC_1 6
#define CUSTOM_FRONTIER_MON_BUTTERFREE_GENERIC_2 7
#define CUSTOM_FRONTIER_MON_BEEDRILL_GENERIC_1 8
#define CUSTOM_FRONTIER_MON_BEEDRILL_GENERIC_2 9
#define CUSTOM_FRONTIER_MON_PIDGEOT_GENERIC_1 10
#define CUSTOM_FRONTIER_MON_PIDGEOT_GENERIC_2 11
#define CUSTOM_FRONTIER_MON_RATICATE_GENERIC_1 12
#define CUSTOM_FRONTIER_MON_RATICATE_GENERIC_2 13
#define CUSTOM_FRONTIER_MON_RATICATE_ALOLA_GENERIC_1 14
#define CUSTOM_FRONTIER_MON_RATICATE_ALOLA_GENERIC_2 15
#define CUSTOM_FRONTIER_MON_FEAROW_GENERIC_1 16
#define CUSTOM_FRONTIER_MON_FEAROW_GENERIC_2 17
#define CUSTOM_FRONTIER_MON_ARBOK_GENERIC_1 18
#define CUSTOM_FRONTIER_MON_ARBOK_GENERIC_2 19
#define CUSTOM_FRONTIER_MON_RAICHU_GENERIC_1 20
#define CUSTOM_FRONTIER_MON_RAICHU_GENERIC_2 21
#define CUSTOM_FRONTIER_MON_RAICHU_ALOLA_GENERIC_1 22
#define CUSTOM_FRONTIER_MON_RAICHU_ALOLA_GENERIC_2 23
#define CUSTOM_FRONTIER_MON_SANDSLASH_GENERIC_1 24
#define CUSTOM_FRONTIER_MON_SANDSLASH_GENERIC_2 25
#define CUSTOM_FRONTIER_MON_SANDSLASH_ALOLA_GENERIC_1 26
#define CUSTOM_FRONTIER_MON_SANDSLASH_ALOLA_GENERIC_2 27
#define CUSTOM_FRONTIER_MON_NIDOQUEEN_GENERIC_1 28
#define CUSTOM_FRONTIER_MON_NIDOQUEEN_GENERIC_2 29
#define CUSTOM_FRONTIER_MON_NIDOKING_GENERIC_1 30
#define CUSTOM_FRONTIER_MON_NIDOKING_GENERIC_2 31
#define CUSTOM_FRONTIER_MON_CLEFABLE_GENERIC_1 32
#define CUSTOM_FRONTIER_MON_CLEFABLE_GENERIC_2 33
#define CUSTOM_FRONTIER_MON_NINETALES_GENERIC_1 34
#define CUSTOM_FRONTIER_MON_NINETALES_GENERIC_2 35
#define CUSTOM_FRONTIER_MON_NINETALES_ALOLA_GENERIC_1 36
#define CUSTOM_FRONTIER_MON_NINETALES_ALOLA_GENERIC_2 37
#define CUSTOM_FRONTIER_MON_WIGGLYTUFF_GENERIC_1 38
#define CUSTOM_FRONTIER_MON_WIGGLYTUFF_GENERIC_2 39
#define CUSTOM_FRONTIER_MON_VILEPLUME_GENERIC_1 40
#define CUSTOM_FRONTIER_MON_VILEPLUME_GENERIC_2 41
#define CUSTOM_FRONTIER_MON_PARASECT_GENERIC_1 42
#define CUSTOM_FRONTIER_MON_PARASECT_GENERIC_2 43
#define CUSTOM_FRONTIER_MON_VENOMOTH_GENERIC_1 44
#define CUSTOM_FRONTIER_MON_VENOMOTH_GENERIC_2 45
#define CUSTOM_FRONTIER_MON_DUGTRIO_GENERIC_1 46
#define CUSTOM_FRONTIER_MON_DUGTRIO_GENERIC_2 47
#define CUSTOM_FRONTIER_MON_DUGTRIO_ALOLA_GENERIC_1 48
#define CUSTOM_FRONTIER_MON_DUGTRIO_ALOLA_GENERIC_2 49
#define CUSTOM_FRONTIER_MON_PERSIAN_GENERIC_1 50
#define CUSTOM_FRONTIER_MON_PERSIAN_GENERIC_2 51
#define CUSTOM_FRONTIER_MON_PERSIAN_ALOLA_GENERIC_1 52
#define CUSTOM_FRONTIER_MON_PERSIAN_ALOLA_GENERIC_2 53
#define CUSTOM_FRONTIER_MON_GOLDUCK_GENERIC_1 54
#define CUSTOM_FRONTIER_MON_GOLDUCK_GENERIC_2 55
#define CUSTOM_FRONTIER_MON_ARCANINE_GENERIC_1 56
#define CUSTOM_FRONTIER_MON_ARCANINE_GENERIC_2 57
#define CUSTOM_FRONTIER_MON_ARCANINE_HISUI_GENERIC_1 58
#define CUSTOM_FRONTIER_MON_ARCANINE_HISUI_GENERIC_2 59
#define CUSTOM_FRONTIER_MON_POLIWRATH_GENERIC_1 60
#define CUSTOM_FRONTIER_MON_POLIWRATH_GENERIC_2 61
#define CUSTOM_FRONTIER_MON_ALAKAZAM_GENERIC_1 62
#define CUSTOM_FRONTIER_MON_ALAKAZAM_GENERIC_2 63
#define CUSTOM_FRONTIER_MON_MACHAMP_GENERIC_1 64
#define CUSTOM_FRONTIER_MON_MACHAMP_GENERIC_2 65
#define CUSTOM_FRONTIER_MON_VICTREEBEL_GENERIC_1 66
#define CUSTOM_FRONTIER_MON_VICTREEBEL_GENERIC_2 67
#define CUSTOM_FRONTIER_MON_TENTACRUEL_GENERIC_1 68
#define CUSTOM_FRONTIER_MON_TENTACRUEL_GENERIC_2 69
#define CUSTOM_FRONTIER_MON_GOLEM_GENERIC_1 70
#define CUSTOM_FRONTIER_MON_GOLEM_GENERIC_2 71
#define CUSTOM_FRONTIER_MON_GOLEM_ALOLA_GENERIC_1 72
#define CUSTOM_FRONTIER_MON_GOLEM_ALOLA_GENERIC_2 73
#define CUSTOM_FRONTIER_MON_RAPIDASH_GENERIC_1 74
#define CUSTOM_FRONTIER_MON_RAPIDASH_GENERIC_2 75
#define CUSTOM_FRONTIER_MON_SLOWBRO_GENERIC_1 76
#define CUSTOM_FRONTIER_MON_SLOWBRO_GENERIC_2 77
#define CUSTOM_FRONTIER_MON_SLOWBRO_GALAR_GENERIC_1 78
#define CUSTOM_FRONTIER_MON_SLOWBRO_GALAR_GENERIC_2 79
#define CUSTOM_FRONTIER_MON_FARFETCHD_GENERIC_1 80
#define CUSTOM_FRONTIER_MON_FARFETCHD_GENERIC_2 81
#define CUSTOM_FRONTIER_MON_DODRIO_GENERIC_1 82
#define CUSTOM_FRONTIER_MON_DODRIO_GENERIC_2 83
#define CUSTOM_FRONTIER_MON_DEWGONG_GENERIC_1 84
#define CUSTOM_FRONTIER_MON_DEWGONG_GENERIC_2 85
#define CUSTOM_FRONTIER_MON_MUK_GENERIC_1 86
#define CUSTOM_FRONTIER_MON_MUK_GENERIC_2 87
#define CUSTOM_FRONTIER_MON_MUK_ALOLA_GENERIC_1 88
#define CUSTOM_FRONTIER_MON_MUK_ALOLA_GENERIC_2 89
#define CUSTOM_FRONTIER_MON_CLOYSTER_GENERIC_1 90
#define CUSTOM_FRONTIER_MON_CLOYSTER_GENERIC_2 91
#define CUSTOM_FRONTIER_MON_GENGAR_GENERIC_1 92
#define CUSTOM_FRONTIER_MON_GENGAR_GENERIC_2 93
#define CUSTOM_FRONTIER_MON_HYPNO_GENERIC_1 94
#define CUSTOM_FRONTIER_MON_HYPNO_GENERIC_2 95
#define CUSTOM_FRONTIER_MON_KINGLER_GENERIC_1 96
#define CUSTOM_FRONTIER_MON_KINGLER_GENERIC_2 97
#define CUSTOM_FRONTIER_MON_ELECTRODE_GENERIC_1 98
#define CUSTOM_FRONTIER_MON_ELECTRODE_GENERIC_2 99
#define CUSTOM_FRONTIER_MON_ELECTRODE_HISUI_GENERIC_1 100
#define CUSTOM_FRONTIER_MON_ELECTRODE_HISUI_GENERIC_2 101
#define CUSTOM_FRONTIER_MON_EXEGGUTOR_GENERIC_1 102
#define CUSTOM_FRONTIER_MON_EXEGGUTOR_GENERIC_2 103
#define CUSTOM_FRONTIER_MON_EXEGGUTOR_ALOLA_GENERIC_1 104
#define CUSTOM_FRONTIER_MON_EXEGGUTOR_ALOLA_GENERIC_2 105
#define CUSTOM_FRONTIER_MON_MAROWAK_GENERIC_1 106
#define CUSTOM_FRONTIER_MON_MAROWAK_GENERIC_2 107
#define CUSTOM_FRONTIER_MON_MAROWAK_ALOLA_GENERIC_1 108
#define CUSTOM_FRONTIER_MON_MAROWAK_ALOLA_GENERIC_2 109
#define CUSTOM_FRONTIER_MON_HITMONLEE_GENERIC_1 110
#define CUSTOM_FRONTIER_MON_HITMONLEE_GENERIC_2 111
#define CUSTOM_FRONTIER_MON_HITMONCHAN_GENERIC_1 112
#define CUSTOM_FRONTIER_MON_HITMONCHAN_GENERIC_2 113
#define CUSTOM_FRONTIER_MON_WEEZING_GENERIC_1 114
#define CUSTOM_FRONTIER_MON_WEEZING_GENERIC_2 115
#define CUSTOM_FRONTIER_MON_WEEZING_GALAR_GENERIC_1 116
#define CUSTOM_FRONTIER_MON_WEEZING_GALAR_GENERIC_2 117
#define CUSTOM_FRONTIER_MON_KANGASKHAN_GENERIC_1 118
#define CUSTOM_FRONTIER_MON_KANGASKHAN_GENERIC_2 119
#define CUSTOM_FRONTIER_MON_SEAKING_GENERIC_1 120
#define CUSTOM_FRONTIER_MON_SEAKING_GENERIC_2 121
#define CUSTOM_FRONTIER_MON_STARMIE_GENERIC_1 122
#define CUSTOM_FRONTIER_MON_STARMIE_GENERIC_2 123
#define CUSTOM_FRONTIER_MON_MR_MIME_GENERIC_1 124
#define CUSTOM_FRONTIER_MON_MR_MIME_GENERIC_2 125
#define CUSTOM_FRONTIER_MON_JYNX_GENERIC_1 126
#define CUSTOM_FRONTIER_MON_JYNX_GENERIC_2 127
#define CUSTOM_FRONTIER_MON_PINSIR_GENERIC_1 128
#define CUSTOM_FRONTIER_MON_PINSIR_GENERIC_2 129
#define CUSTOM_FRONTIER_MON_TAUROS_GENERIC_1 130
#define CUSTOM_FRONTIER_MON_TAUROS_GENERIC_2 131
#define CUSTOM_FRONTIER_MON_TAUROS_PALDEA_COMBAT_GENERIC_1 132
#define CUSTOM_FRONTIER_MON_TAUROS_PALDEA_COMBAT_GENERIC_2  133
#define CUSTOM_FRONTIER_MON_TAUROS_PALDEA_AQUA_GENERIC_1 134
#define CUSTOM_FRONTIER_MON_TAUROS_PALDEA_AQUA_GENERIC_2 135
#define CUSTOM_FRONTIER_MON_TAUROS_PALDEA_BLAZE_GENERIC_1 136
#define CUSTOM_FRONTIER_MON_TAUROS_PALDEA_BLAZE_GENERIC_2 137
#define CUSTOM_FRONTIER_MON_GYARADOS_GENERIC_1 138
#define CUSTOM_FRONTIER_MON_GYARADOS_GENERIC_2 139
#define CUSTOM_FRONTIER_MON_LAPRAS_GENERIC_1 140
#define CUSTOM_FRONTIER_MON_LAPRAS_GENERIC_2 141
#define CUSTOM_FRONTIER_MON_VAPOREON_GENERIC_1 142
#define CUSTOM_FRONTIER_MON_VAPOREON_GENERIC_2 143
#define CUSTOM_FRONTIER_MON_JOLTEON_GENERIC_1 144
#define CUSTOM_FRONTIER_MON_JOLTEON_GENERIC_2 145
#define CUSTOM_FRONTIER_MON_FLAREON_GENERIC_1 146
#define CUSTOM_FRONTIER_MON_FLAREON_GENERIC_2 147
#define CUSTOM_FRONTIER_MON_OMASTAR_GENERIC_1 148
#define CUSTOM_FRONTIER_MON_OMASTAR_GENERIC_2 149
#define CUSTOM_FRONTIER_MON_KABUTOPS_GENERIC_1 150
#define CUSTOM_FRONTIER_MON_KABUTOPS_GENERIC_2 151
#define CUSTOM_FRONTIER_MON_AERODACTYL_GENERIC_1 152
#define CUSTOM_FRONTIER_MON_AERODACTYL_GENERIC_2 153
#define CUSTOM_FRONTIER_MON_SNORLAX_GENERIC_1 154
#define CUSTOM_FRONTIER_MON_SNORLAX_GENERIC_2 155
#define CUSTOM_FRONTIER_MON_ARTICUNO_GENERIC_1 156
#define CUSTOM_FRONTIER_MON_ARTICUNO_GENERIC_2 157
#define CUSTOM_FRONTIER_MON_ARTICUNO_GALAR_GENERIC_1 158
#define CUSTOM_FRONTIER_MON_ARTICUNO_GALAR_GENERIC_2 159
#define CUSTOM_FRONTIER_MON_ZAPDOS_GENERIC_1 160
#define CUSTOM_FRONTIER_MON_ZAPDOS_GENERIC_2 161
#define CUSTOM_FRONTIER_MON_ZAPDOS_GALAR_GENERIC_1 162
#define CUSTOM_FRONTIER_MON_ZAPDOS_GALAR_GENERIC_2 163
#define CUSTOM_FRONTIER_MON_MOLTRES_GENERIC_1 164
#define CUSTOM_FRONTIER_MON_MOLTRES_GENERIC_2 165
#define CUSTOM_FRONTIER_MON_MOLTRES_GALAR_GENERIC_1 166
#define CUSTOM_FRONTIER_MON_MOLTRES_GALAR_GENERIC_2 167
#define CUSTOM_FRONTIER_MON_DRAGONITE_GENERIC_1 168
#define CUSTOM_FRONTIER_MON_DRAGONITE_GENERIC_2 169
#define CUSTOM_FRONTIER_MON_MEW_GENERIC_1 170
#define CUSTOM_FRONTIER_MON_MEW_GENERIC_2 171
#define CUSTOM_FRONTIER_MON_DITTO_GENERIC_1 172
#define CUSTOM_FRONTIER_MON_DITTO_GENERIC_2 173
#define CUSTOM_FRONTIER_MON_RAPIDASH_GALAR_GENERIC_1 174
#define CUSTOM_FRONTIER_MON_RAPIDASH_GALAR_GENERIC_2 175

#define NUM_CUSTOM_FRONTIER_GENERIC_MONS 176

//Support Mons

//Sun Setter Mons

//Sun Abuser Mons

//Rain Setter Mons

//Rain Abuser Mons

#define CUSTOM_FRONTIER_MON_LUVDISC_RAIN_ABUSER_1 0

//Sand Setter Mons

//Sand Abuser Mons

//Snow Setter Mons

//Snow Abuser Mons

//Psyspam Setter Mons

//Psyspam Abuser Mons

//Trick Room Setter Mons

//Trick Room Abuser Mons

//Generic Restricted Mons

//Sun Setter Restricted Mons

//Sun Abuser Restricted Mons

//Rain Setter Restricted Mons

//Rain Abuser Restricted Mons

//Sand Setter Restricted Mons

//Sand Abuser Restricted Mons

//Snow Setter Restricted Mons

//Snow Abuser Restricted Mons

//Psyspam Setter Restricted Mons

//Psyspam Abuser Restricted Mons

//Trick Room Setter Restricted Mons

//Trick Room Abuser Restricted Mons

//Generic Tera Mons

//Sun Setter Tera Mons

//Sun Abuser Tera Mons

//Rain Setter Tera Mons

//Rain Abuser Tera Mons

//Sand Setter Tera Mons

//Sand Abuser Tera Mons

//Snow Setter Tera Mons

//Snow Abuser Tera Mons

//Psyspam Setter Tera Mons

//Psyspam Abuser Tera Mons

//Trick Room Setter Tera Mons

//Trick Room Abuser Tera Mons

//Generic Mega Mons

//Sun Setter Mega Mons

//Sun Abuser Mega Mons

//Rain Setter Mega Mons

//Rain Abuser Mega Mons

//Sand Setter Mega Mons

//Sand Abuser Mega Mons

//Snow Setter Mega Mons

//Snow Abuser Mega Mons

//Psyspam Setter Mega Mons

//Psyspam Abuser Mega Mons

//Trick Room Setter Mega Mons

//Trick Room Abuser Mega Mons


#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_CUSTOM_MONS_H