gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Emerald Squared!\p"
	.string "My name is BIRCH.\p"
	.string "But you probably already knew that\n"
	.string "at this point.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "them, from regions around the world.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "In this hack, you will raise, train,\n"
	.string "and battle against many trainers.\p"
	.string "Nearly every battle is a double\n"
	.string "battle, just like the gamecube\l"
	.string "spinoff games Colisseum and XD.\p"
	.string "There are level caps and other,\n"
	.string "subtler ways of difficulty culling.\p"
	.string "However, there are just as many QoL\n"
	.string "changes to help smooth things out.\p"
	.string "There are new areas, hidden items,\n"
	.string "and many more things to discover,\l"
	.string "So explore to your heart's content!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!$"
