MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Boo!\n"
	.string "Gotcha!\p"
	.string "I faked you out didn't I!\n"
	.string "Do you think one of your partners\l"
	.string "would want to learn to do that too?.\p"
	.string "I can do it!\p"
	.string "If you'd like, I'll teach the move\n"
	.string "Fake Out to a POKéMON of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which POKéMON wants to\n"
	.string "learn how to Fake Out?$"

MoveTutor_Text_SwaggerTaught:
	.string "Have fun spooking your opponents!\n"
	.string "I know I do!.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can use your\n"
	.string "foe's power against them?\l"
	.string "It's really easy!\p"
	.string "Do you think your POKéMON will\n"
	.string "want to do that?\p"
	.string "I can teach one the move Counter\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Hit 'em back!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON clapped cheeks back.$"

MoveTutor_Text_RolloutTaught:
	.string "Let those enemy mons know what hit\n"
	.string "them. Good luck!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Man, rock type moves suck they have.\n"
	.string "high damage but often just miss.\p"
	.string "But hey! I know one that doesn't\n"
	.string "usually miss, and it can drop defense!\p"
	.string "It's called Stone Strike.\n"
	.string "Want me to teach it to a POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I feel relieved when seeing moves\n"
	.string "hit with consistency!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one. But your are\n"
	.string "following my eyes and movements,\l"
	.string "yes? Watching me act strange?\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move Follow Me?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach it\n"
	.string "to your POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the POKéMON\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught:
	.string "Follow Me is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_AllySwitchTeach:
	.string "Ah, young one!\p"
	.string "How would you like to teach one of\n"
	.string "your partners a neat trick?\l"
	.string "It's called ALLY SWITCH!$"

MoveTutor_Text_AllySwitchDeclined:
	.string "Fufufu, very well. Come learn it\n"
	.string "anytime!$"

MoveTutor_Text_AllySwitchWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the POKéMON\l"
	.string "you wish me to teach.$"

MoveTutor_Text_AllySwitchTaught:
	.string "Ally Switch is a move of trickery.\p"
	.string "Could you execute it to perfection\n"
	.string "and go far…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "some rich people to take from?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move Snatch.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will thieve good moves. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife always leaves when\n"
	.string "we argue, walking out the door.\p"
	.string "She flips me the bird and gives me,\n"
	.string "a Parting Shot.\p"
	.string "I can teach your POKéMON how to\n"
	.string "do it too. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Well screw you too buddy!$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Good!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I would be happy if she quit doing\n"
	.string "that stupid thing.$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if I could soak it all in,\l"
	.string "holding back the forces of nature.\p"
	.string "Of course it's not possible.\n"
	.string "At least not for me…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn Wide Guard?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\n"
	.string "Okay...$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach Wide Guard?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
