voice_group camel_by_camel_drumset, 35
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 0 @ 35
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 0 @ 36
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 0 @ 37
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 0 @ 38
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 255, 242 @ 39
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_unknown_synth_snare, 255, 0, 255, 0 @ 40
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 41
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 0, 255, 0 @ 42
	voice_directsound 57, 69, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 43
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 0, 255, 0 @ 44
	voice_directsound 54, 64, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 45
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 0, 255, 0 @ 46
	voice_directsound 57, 69, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 47
	voice_directsound 60, 79, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 48
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 0, 255, 234 @ 49
	.rept 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 0, 255, 234 @ 52
	.rept 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 0, 255, 234 @ 55
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 0, 255, 234 @ 57
	.rept 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 72, 94, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0 @ 61
	voice_directsound_no_resample 72, 104, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0 @ 62
	voice_directsound_no_resample 72, 94, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0 @ 63
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0 @ 64
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0 @ 65
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0 @ 66
	.rept 13
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_open_triangle, 255, 0, 255, 0 @ 80
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_open_triangle, 255, 0, 255, 0 @ 81
	.rept 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 0 @ 85
