voice_group fire_and_flames_drumset, 35
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 35
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 36
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 37
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 38
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 39
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_unknown_synth_snare, 255, 0, 255, 0 @ 40
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 216, 77, 204 @ 41
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_fire_and_flames_close_hihat, 255, 127, 0, 188 @ 42
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 43
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_fire_and_flames_close_hihat, 255, 127, 0, 188 @ 44
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 45
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_fire_and_flames_open_hihat, 255, 242, 141, 0 @ 46
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 47
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 48
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 49
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_fire_and_flames_open_hihat, 255, 242, 141, 0 @ 51
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 52
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_trinity_cymbal_crash, 255, 246, 0, 216 @ 53
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 54
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 55
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 56
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 57
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 59
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 60
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 62
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 63
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 74
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 75
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 80
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 85
