voice_group live_and_learn_drumset, 34
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 34
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 35
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 36
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 37
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242 @ 38
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 39
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_unknown_synth_snare, 255, 0, 255, 0 @ 40
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 216, 77, 204 @ 41
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 42
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 216, 77, 204 @ 43
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 44
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 216, 77, 204 @ 45
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 242, 141, 0 @ 46
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 242, 141, 0 @ 47
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 48
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 49
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 51
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 52
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 53
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 54
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 55
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 56
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 57
