voice_group megalovania_drumset, 36
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 36
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242 @ 37
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242 @ 38
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 255, 242 @ 39
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_unknown_synth_snare, 255, 0, 255, 0 @ 40
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 41
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 0, 255, 0 @ 42
	voice_directsound 57, 69, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 43
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 0, 255, 0 @ 44
	voice_directsound 54, 64, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 45
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_megalovania_open_hihat_quiet, 255, 0, 255, 0 @ 46
	voice_directsound 57, 69, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 47
	voice_directsound 60, 79, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 0 @ 48
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_megalovania_orchestra_cymbal_crash_quiet, 255, 246, 0, 216 @ 49
