voice_group nightcall_drumset, 35
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242 @ 35
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 36
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 37
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242 @ 38
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 39
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 41
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 42
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 43
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 44
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 45
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 46
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 47
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 48
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 49
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 51
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 52
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 53
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 54
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 @ 55
