Agartha_Hub_MapScripts::
	.byte 0

Agartha_Hub_EventScript_KantoLab::
	msgbox Agartha_Hub_Text_KantoLab, MSGBOX_SIGN
	end

Agartha_Hub_Text_KantoLab:
	.string "Forsaken Laboratory$"

Agartha_Hub_EventScript_DistortionWorld::
	msgbox Agartha_Hub_Text_DistortionWorld, MSGBOX_SIGN
	end

Agartha_Hub_Text_DistortionWorld:
	.string "The sign is written in an\n"
	.string "incomprehensible language.$"

Agartha_Hub_EventScript_UnovanRuins::
	msgbox Agartha_Hub_Text_UnovanRuins, MSGBOX_SIGN
	end

Agartha_Hub_Text_UnovanRuins:
	.string "Silent Ruins$"

Agartha_Hub_EventScript_KalosianMeadow::
	msgbox Agartha_Hub_Text_KalosianMeadow, MSGBOX_SIGN
	end

Agartha_Hub_Text_KalosianMeadow:
	.string "Ancient Meadow$"

Agartha_Hub_EventScript_UltraSpaceSea::
	msgbox Agartha_Hub_Text_UltraSpaceSea, MSGBOX_SIGN
	end

Agartha_Hub_Text_UltraSpaceSea:
	.string "Otherworldly Sea$"

Agartha_Hub_EventScript_DeepWeald::
	msgbox Agartha_Hub_Text_DeepWeald, MSGBOX_SIGN
	end

Agartha_Hub_Text_DeepWeald:
	.string "Deep Weald$"

Agartha_Hub_EventScript_CrystalCaverns::
	msgbox Agartha_Hub_Text_CrystalCaverns, MSGBOX_SIGN
	end

Agartha_Hub_Text_CrystalCaverns:
	.string "Crystal Caverns$"